apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: sift
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: worker
      app.kubernetes.io/part-of: sift
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker
        app.kubernetes.io/part-of: sift
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: sift-backend:rss-cache-v3
          imagePullPolicy: IfNotPresent
          command: ["python", "worker.py"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsGroup: 10001
            runAsUser: 10001
          envFrom:
            - configMapRef:
                name: sift-config
            - secretRef:
                name: sift-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
